### ISSUE TITLE
[Bug] Random Crashing/Stuttering

### ISSUE THREAD

**Issue by seniorm0ment** [NO-ob/LoliSnatcher_Droid#45] opened 2021-04-15 02:22 UTC
Not sure the cause, however I experience crashes very often. It is random.
It seems like it might possibly be some kind of cache or memory issue.
When I scroll fast through thumbnails, or am in viewer mode and swipe fairly fast sometimes it crashes, other times not. Sometimes when playing a video it starts stuttering or freezing (not like a network issue, like a performance issue), then it would resolve or crash the app. Sometimes if I rotate the device during the stuttering it rotates then crashes.
It's seemingly random, and I can't reproduce it.

 v1.8.0, LGv40, Android 10

**Comment by ZutgKcjA** [comment] 2021-04-19 12:16
I am absolutely experiencing the same issue. I thought I was the only one. 
I believe it is caused by downloading pictures and looking at other pictures at the same time. This is the way my app crashes most often anyway, when a download finishes while another picture is loading. It causes a lag spike, which often does not resolve but instead causes the app to lag and stutter, then freeze and crash. 
I also dont know the cause, but I would agree that it feels like a memory issue. 

I am on version 1.8.1 (Android 10)

**Comment by NO-ob** [comment] 2021-04-21 22:21
Hi im not gonna be able to take a look at this for a few weeks, if you're using the staggered view for the image previews id recommend disabling it, the library for it was leaking memory. If you find other reproducible things causing the crashes plox post them here as they should be useful. Thanks

**Comment by seniorm0ment** [comment] 2021-04-21 22:47
I wasn't on staggered view.
I tried playing around with the image preload count, as well as changing thumbnails to sample.
I notice the amount of crashing increases the higher I set the preload count (say just going from 3 to 5), lowering it back down seems to decrease the amount.

**Comment by NO-ob** [comment] 2021-04-22 07:46
Might be worth trying the my device is shit box, it disables the loading animations and the new http lib, it will set the gallery mode to sample and your preload count to 0 also so you might wanna put those back to your normal settings after, Just to note i dont experience crashing and have my preload count set to 2 so it might be worth using that number also

**Comment by ZutgKcjA** [comment] 2021-04-22 09:19
After some more testing: 
There are significantly fewer crashes on version 1.8.1 than there are on version 1.8.0 (due to memory usage improvements?).
Crashes are still an issue depending on the gallery that I'm viewing. 

It appears the crashes happen most often in galleries where all image files are very large (>10 MB). The app seems to get overwhelmed trying to load many large files at once.
The frequency of the crashes is increased when I enable the caches in the settings (especially media cache). 

Crashes also happen (seemingly at random) when I: 
- browse quickly through a gallery
- download many files in quick succession. 

I feel like I have a reasonably powerful device which should be able to deal with these situations handily.

**Comment by seniorm0ment** [comment] 2021-05-17 12:39
Yeah I've noticed seemingly less crashes, that being said they do happen on occasion. Also same I have a flagship device, although like a year and a half old it should be fine. It could be hitting memory issues though due to other stuff in the background.

**Comment by NO-ob** [comment] 2021-06-22 11:00
What value are you using for the gallery view preload?

**Comment by seniorm0ment** [comment] 2021-06-22 11:39
Currently at 2

**Comment by ZutgKcjA** [comment] 2021-07-14 21:24
I still get occasional crashes on the new version associated in particular with large file sizes. The crashes have become even less frequent on the new version, without knowing what has changed. 
I don't like to believe it has to do my particular device, as I can load several large files at once via Chrome without experiencing crashes. I would not rule out a memory leak issue.

**Comment by seniorm0ment** [comment] 2021-07-14 21:44
can confirm, I notice issues when loading videos.
Definitely still seems like it might be a memory leak issue

**Comment by NANI-SORE** [comment] 2021-07-15 23:02
@seniorm0ment @ZutgKcjA
Examples would be nice
In the next version app will start reencoding images if their resolution is bigger than the screen's resolution (it already did this before, but now it will be more aggressive), should help with memory usage. Not sure if anything can be done with huge videos

**Comment by seniorm0ment** [comment] 2021-07-16 17:27
Examples in what sense? 
It seems kinda random.
Could an option for debugging and log viewing/copying be added into the next Lolisnatcher release then we can easily diagnose these issues (without needing to install a seperate version). Adb is a little annoying without root tbh

**Comment by NANI-SORE** [comment] 2021-07-16 22:07
Examples of large files/videos which consistently lead to noticeable issues, if possible. I already added a debug option for performance overlay for the next version, I'll see about adding a log viewer/dumper too.

Reencoding is used to decrease image size in memory if its too big, I don't think we ever got a report of files not opening correctly.

**Comment by ZutgKcjA** [comment] 2021-08-02 17:16
Hmm, there are no files in particular which consistently cause issues. I know the app crashes relatively reliably when trying to download video files larger than 200 MB (Gelbooru seemingly allows file uploads larger than 1 GB even). Although it isn't even videos that are the problem, they play just fine regardless of file size. The problem presumably lies with very large image files. 
Unfortunately Gelbooru doesn't allow sorting by file size, but you could try to search "sort:height -animated" or "sort:width -animated" and seeing whether you crash. 
If you wish to test e621 (where the file size limit is 100 MB), you could actually sort the files by size using "order:filesize -animated".

The most reliable method to provoke a crash I've found is to load lots of pages in very quick succession (20-30 pages should suffice). Just drag the scroll bar down again and again in waterfall view until you crash.

**Comment by aknight2015** [comment] 2022-01-05 21:23
I have the same issue. It appears to be a memory issue. It will use over 400 megs of memory and then crash. Also, new update isn't taking. I install the update, fire up the app, says update available.

**Comment by NANI-SORE** [comment] 2022-01-07 11:52
The last release had some performance fixes and now files larger than 200mb will not start loading until user confirms it.
I still can't guarantee that the app won't crash during decoding of huge images since there is a huge memory usage spike at that moment and different devices can have different reactions to that event. For example I could reproduce a simillar hard crash on my phone only when I had two huge 4k videos buffering at the same time, but images never caused any crashes, no matter how big they are or how many of them were loaded.

**Comment by seniorm0ment** [comment] 2022-01-15 21:42
I've been noticing a significantly higher amount of crashes with the new update. Also I used to be able to play very large files no issues, now I can barely load without them crashing after I click start.

**Comment by NANI-SORE** [comment] 2022-01-16 10:19
@seniorm0ment 
I've encountered some crashes recently too, but I can reproduce them only on my phone.
Can you please enable Performance graph in debug settings (tap version multiple times to access them), return to main screen and see if graph keeps going when nothing is happening

**Comment by seniorm0ment** [comment] 2022-01-16 10:24
The bar moving across? It stops, but then goes very very little then stops then goes very very little, etc.
But compared to when I do stuff, the bar moves smoothly through so no it doesn't seem to keep going when I'm doing nothing

**Comment by NANI-SORE** [comment] 2022-01-16 10:48
Ok, then it's probably not related to this problem. Out of all my devices my phone is the only one where graph keeps going even when nothing is happening and the only device where crashes happen.
Can you try opening your phone settings -> developer settings -> running services, open it in split screen mode with the app and try scrolling through like 50 images in gallery view and then close it?
Will the memory usage go way up and won't go down after returning to the thumbnails view?

**Comment by seniorm0ment** [comment] 2022-01-16 11:22
It seems to go up very very quickly from like 200mb to over a gig while swiping in gallery view. Then drops down when I back out to thumbnail.
I tried playing a few large videos, and it was only sitting at like 600mb.
However I started swiping very fast through gallery view nonstop, and as the ram increased to lile 0.91gb the app just froze and crashed. Not even large videos, just pictures maybe with a few small videos between.

**Comment by NANI-SORE** [comment] 2022-01-16 11:27
Thanks, that confirms that there is a possible memory leak in gallery view.
Very strange that it happens only for some devices.
I'll keep investigating the issue and post here when the fix will be found.

**Comment by NANI-SORE** [comment] 2022-01-16 13:40
I think I found the reason, the check responsible for clearing out of view items didn't work properly, I'll test it (and some other changes) a bit and we'll release a build soon.

**Comment by NANI-SORE** [comment] 2022-01-17 20:44
@seniorm0ment 
Release 2.2.0 with a fix for this is out

**Comment by seniorm0ment** [comment] 2022-01-17 21:34
will take a peek when it's pushed to f-droid, and report back thanks!

**Closed** 2022-03-12 10:19 UTC
