### ISSUE TITLE
Rule34.us can't be added 

### ISSUE THREAD

**Issue by baraa272** [NO-ob/LoliSnatcher_Droid#153] opened 2022-08-26 22:22 UTC
Rule34.us addition doesn't work at all 
![Screenshot_20220827-004835_LoliSnatcher](https://user-images.githubusercontent.com/32843097/186997149-cbdb0e46-7f82-41cd-bf0b-22b62e11c738.png)

**Comment by makoto-kokoroki** [comment] 2024-05-20 21:07
This isn't the devs fault and I believe rule34.us actually restricts access to their website thru a lot of diff ports and the website is slow as shit anyway. It has never worked for most apps that have been made to browse boorus.

You should consider using rule34.xxx if your interests lie within that realm. It has more content, loads faster, and is just in general "usually" going to work.

**Comment by NANI-SORE** [comment] 2024-10-22 11:11
We don't have r34us support yet, duplicate of #91

**Closed by NANI-SORE** 2024-10-22 11:11 UTC
