### ISSUE TITLE
[Bug] Volume scroll broken in 1.8.1

### ISSUE THREAD

**Issue by FlipperLP** [NO-ob/LoliSnatcher_Droid#50] opened 2021-05-31 08:18 UTC
So first, it took me quite some time to find a mobile client capable of using the szurubooru API, so probs to the coder - amazing app. Keep up the good work ^^

But I still have a little bug to report. Not sure if it's my phone, but the setting "Use Volume Buttons for Scrolling" is not working for me. Am I missing out on something I need to tweak in the settings first to get it to work?
I'm using a Samsung Galaxy 8 with Android 9.

**What's supposed to happen:**
Being able to use the Volume Buttons on the side of the phone to scroll through the images.

**What's actually happening:**
The volume buttons control the volume

**Comment by FlipperLP** [comment] 2021-05-31 08:33
So I just tested it further, and it seems to not work when:

- the picture is a GIF
- the picture is a video (regardless, of the control bar being visible or not)
- swiped from a video to a picture (when swiped twice so the "post" is surrounded by other pictures, it works)

It strangely also works when the post is next to a video/GIF, but the video/GIF has not been seen yet.

**Comment by NANI-SORE** [comment] 2021-06-03 19:39
Yeah, I didn't test this feature properly before releasing it (though switching to volume control when on videos with visible toolbar is intended behavior).
Sorry for that.
I think I already fixed it on my build, but I won't release the fix (and a bunch of other stuff) until I have time to test it all later next week.

**Comment by NANI-SORE** [comment] 2021-07-06 13:25
Should be fixed in 1.8.2 + I added volume scrolling to the preview grid

**Closed** 2022-03-12 10:19 UTC
