### ISSUE TITLE
Lag and Crashes new UI update

### ISSUE THREAD

**Issue by ghost** [NO-ob/LoliSnatcher_Droid#97] opened 2022-02-17 19:00 UTC
Hi,

I've been having lag and Crashes,freezes with the new UI update you rolled around a couple of months ago. This wasn't a problem with the old UI. I'm not sure what the problem is. I have a Samsung Galaxy S9 running Android 10. I have low performance mode enabled, it hasn't helped. It doesn't matter how many tabs I have on the side. Even with 1 tab, it'll still lag and freeze as I scroll down the pictures. It even freezes in the middle of a video. Any help? Thanks man.

**Comment by NANI-SORE** [comment] 2022-02-17 19:31
Are you on version 2.2.0? There was a common memory leak since 2.0 which we fixed in 2.2

**Comment by dkdjsk** [comment] 2022-02-18 02:29
Yup 2.2.0+170. I noticed when first opening the app, it'll be frozen and it says opening # of tabs. After the tabs are on added, it'll be fine until I start scrolling through the pictures. Then it'll freeze again. For at least a minute. It could freeze at any time. Opening a picture, opening the sidebar, scrolling through the pictures, opening a pixiv link and coming back.

This was not a problem with the old UI. It was super smooth.

**Comment by NANI-SORE** [comment] 2022-02-18 08:12
I think someone mentioned simillar freezes before, they cleared app's cache in system settings and it fixed the problem.
Also you can try disabling isolates (tap on version in settings a few times until debug settings appear and in there enable "Disable Isolates").
If that won't help, try reinstalling completely. Remember to backup your data/settings folder first (/sdcard/Lolisnatcher on Android 10, though it should persist between app installs on Android 10 and below).

I myself encountered some freezes when I was developing 2.0 (which wasn't just a UI rework, almost everything in the backend was changed), but they were really rare and I couldn't reproduce them

**Closed** 2023-07-02 18:34 UTC
