### ISSUE TITLE
Hydrus test unsuccessful despite successful API key request

### ISSUE THREAD

**Issue by horribleCodes** [NO-ob/LoliSnatcher_Droid#162] opened 2022-10-18 19:50 UTC
I tried to add my hydrus network to my boorus, but I can't get past the test. After entering the URL and specifying the Booru type, I was able to get the API key using the "Get Hydrus Api Key" button, so I know the app managed to reach the server. I tried giving the key all permissions and created two more keys for good measure, but I still get the "No Data Returned" error.
User ID is supposed to be blank, correct?

**Comment by Dexkant** [comment] 2022-10-23 03:15
Yeah, I had this issue too, I solved it by using an older version of hydrus, in the v460's I think. I guess the client api in hydrus updated recently. Lolisnatcher will probably need an update to fix it.

**Comment by NO-ob** [comment] 2022-10-23 15:31
Try removing the s from https:// in the url

**Comment by horribleCodes** [comment] 2022-10-23 22:18
> Try removing the s from https:// in the url

I tried that - I couldn't even get the key without it. I also tried getting the key first with https://, and then removing it, but that didn't work either.
I am using Caddy, Tailscale and Duck DNS to host the server, does that help?

**Comment by Dexkant** [comment] 2022-10-24 01:44
I only use hydrus locally with a http link and also get this error. I doubt it has anything to do with http vs. https or Caddy. I'm still pretty sure the issue is due to a Hydrus update.

**Comment by NO-ob** [comment] 2022-10-24 12:52
I will set up hydrus and take a look

**Comment by NO-ob** [comment] 2022-10-26 19:27
Will be fixed in next version

**Closed by NO-ob** 2022-10-26 19:27 UTC
