### ISSUE TITLE
Inkbunny.net doesn't load on 2.4.0 but works on 2.3.3

### ISSUE THREAD

**Issue by RAPXT** [NO-ob/LoliSnatcher_Droid#246] opened 2024-02-08 00:51 UTC
I haven't changed any settings whether on LoliSnatcher nor on my InkBunny account.

I've only made a backup of app settings from 2.3.3 and then imported these settings to 2.4.0 (hotfix 2).

![Screenshot_20240208-015233253](https://github.com/NO-ob/LoliSnatcher_Droid/assets/53192319/2d23b5e5-2b99-4b29-a7b0-eaa62d860c1c)

Imported e621 account from 2.3.3 works without issues.

**Comment by NANI-SORE** [comment] 2024-02-08 10:57
Can't reproduce on my end. Try enabling debug mode (tap version in settings 5 times), then try adding the inkbooru config, then return to the main drawer and press "Open Alice" (shown on screenshot). In there search "api_" and send a screenshot of that. Maybe some requests are failing for you for some reason.

![image](https://github.com/NO-ob/LoliSnatcher_Droid/assets/12685712/185df98d-a351-4a83-840b-eb35a72ae0c7)

**Comment by RAPXT** [comment] 2024-02-08 15:15
![Screenshot_1](https://github.com/NO-ob/LoliSnatcher_Droid/assets/53192319/8ad7017d-cf0d-495f-bf2b-1e752ab1d50f)
![Screenshot_2](https://github.com/NO-ob/LoliSnatcher_Droid/assets/53192319/7668a6da-ab4c-4ea6-b597-f350193d6ee3)
![Screenshot_3](https://github.com/NO-ob/LoliSnatcher_Droid/assets/53192319/339262a9-afb5-4abd-a382-390d500c6fdc)
![Screenshot_4](https://github.com/NO-ob/LoliSnatcher_Droid/assets/53192319/8deeaf6c-7a20-482d-b606-f5bd13281849)

Maybe you could share your Inkbunny booru config without login. Then I could try to add my credentials and import from clipboard.

Could that work?

**Comment by NANI-SORE** [comment] 2024-02-08 16:59
My config is the same as yours, you either
- didn't enable API access in the web (but in this case it's strange that it works on old version) 
- your login/password has some special characters that maybe break when we convert them into a url (tell me what special characters you have there, no need to give me full credentials, for example mine has these three: !@.)
- something else???

**Comment by RAPXT** [comment] 2024-02-08 17:24
API access is check marked in web.

Login/password consists only of dots, letters and numbers. No other special characters are used.

Edit: Tinkered a bit in network settings:
Self signed SSL -> enabled
Enabled the suggested User Agent
Cleared Cookies

Now it works again 🎉🤔

If you want me to, since I have a backup, I could reset and see if I can reproduce what fixed my error.

**Comment by NANI-SORE** [comment] 2024-02-08 17:47
SSL certs and user agent shouldn't affect this, at least I don't have them on and it works, maybe you had some cookies that were messing with requests? We won't know now, cookies are not included in backups

I'll close the issue

**Closed by NANI-SORE** 2024-02-08 17:47 UTC
